// GENERATED by scripts/tracker-version.mjs — do not edit by hand.
//
// The version segment of the tracker's address, derived from the bundle's
// bytes (packages/app/public/v1/tracker.js). New bytes mean a new address,
// so no cache anywhere can hand a freshly served document an old script.
export const TRACKER_VERSION = '731b72f1cd40';
