#!/usr/bin/env node
/* eslint-env node */
/* eslint-disable no-console */
// Regenerates src/tracker-version.ts from the tracker bundle the app serves.
//
// WHY THE ADDRESS CARRIES A HASH. Every served document used to point at the
// one fixed address /v1/tracker.js. Our own zones are purged on each deploy,
// but a customer's own domain can sit behind the CUSTOMER's cache, which we
// cannot purge — measured on 21 September 2026: htmlradar.page served the new
// 24,278-byte tracker while decks.draconic.ai kept serving the previous
// 23,095-byte one for hours, so a new page configuration met an old script and
// a silent reader recorded 0 seconds. Deriving the address from the bytes
// means new bytes are a new address, and no cache anywhere holds that address
// yet.
//
// Run from wrangler's [build] command (wrangler.toml), so every deploy hashes
// the bytes that deploy ships. The generated file is committed as well, and
// tests/tracker-version.test.ts fails when the committed value has drifted —
// so the address is never hand-maintained and never silently stale.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

// The bundle the application actually serves at TRACKER_URL. CI overwrites it
// from packages/tracker/dist/tracker.js before the app build and before this
// worker is deployed, so hashing this file hashes what recipients receive.
export const TRACKER_FILE = new URL('../../app/public/v1/tracker.js', import.meta.url);
export const VERSION_FILE = new URL('../src/tracker-version.ts', import.meta.url);

/** The version segment: the first 12 hex characters of the bundle's SHA-256. */
export const trackerVersion = (bytes) =>
  createHash('sha256').update(bytes).digest('hex').slice(0, 12);

export const versionModule = (version) =>
  [
    '// GENERATED by scripts/tracker-version.mjs — do not edit by hand.',
    '//',
    "// The version segment of the tracker's address, derived from the bundle's",
    '// bytes (packages/app/public/v1/tracker.js). New bytes mean a new address,',
    '// so no cache anywhere can hand a freshly served document an old script.',
    `export const TRACKER_VERSION = '${version}';`,
    '',
  ].join('\n');

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const version = trackerVersion(readFileSync(TRACKER_FILE));
  writeFileSync(VERSION_FILE, versionModule(version));
  console.log(`tracker version: ${version}`);
}
